import { Section, Subsection } from "../components/layout";
import { Heading, Anchor, Text } from "../components/core";

const Implementation = () => (
  <>
    <Heading level={1}>Dainty – Implementation</Heading>
    <Section>
      <Subsection>
        <Text>
          <i>
            This section will be expanded later on. The content below was
            written when only the generator for Visual Studio existed.
          </i>
        </Text>
      </Subsection>
      <Subsection>
        <Text>
          The theme is generated by doing transformations in a pipeline on the
          default color theme, Environment – Fonts and Colors settings, and
          settings for included extensions. Because the dynamics of Dainty is
          similar to that of the default themes, most colors can be changed
          using search–replace. In addition, specific colors can be set
          afterwards to get full control over the styling.
        </Text>
        <Text>
          The palette palette is generated and processed using{" "}
          <Anchor href="https://github.com/Evercoder/culori">Culori</Anchor>. It
          is built by first generating 41-indices scales for each hue. Blue is
          the primary color, and there are four scales based on blue with
          different amounts of chroma. Then colors are selected within the
          scales, preferring indicies divisible by 4. The default colors are
          defined as LCh using math. Overrides expressed as RGB hex colors are
          supported.
        </Text>
      </Subsection>
    </Section>
  </>
);

export default Implementation;
